### ISSUE TITLE
RootDN not being created 

### ISSUE THREAD

**Issue by is-smok** [389ds/ds-container#1]
Running dockerized version with docker-compose does not create RootDN. compose.yaml:
```
services:
  tak-openldap:
    image: 389ds/dirsrv:latest
    volumes:
      - /data/docker/takserver/ldap:/data
    environment:
      SUFFIX_NAME: "dc=mydomain,dc=org"
      DS_ADMIN_USERNAME: "admin"
      DS_ADMIN_PASSWORD: "Password01"
      DS_DM_PASSWORD: "Password01"
    networks:
      tak-network:
        aliases:
          - tak-openldap
    ports:
      - "9389:3389"
      - "9636:3636"
    tty: true
    stdin_open: true
```
No matter if I use env SUFFIX_NAME or DS_SUFFIX_NAME. 
Cannot create new instance as well,  I receive:
```
 dscreate from-file /data/template.ini
Starting installation ...
Validate installation settings ...
Error: [Errno 2] No such file or directory: 'systemd-detect-virt'
```
Host system: Ubuntu Server. Config dir is visible from inside container. I tried to remove everything from /data dir: files has been recreated but no RootDN created still.
Any help?
